Options:
  # If this option is set to true, the tnt will not damage the water
  water-protection: true
  # If this option is set to True, the particles of the explosion will appear
  fake-explosion: true

Messages:
  # Message when the player does not have permission
  no-perm: "&cVous ne pouvez pas faire ceci."

  # Message when the command is not correct
  invalid-usage: "&cL'utilisation de cette commande est incorrecte. Seule la commande /cbp reload est disponible."

  # Message when the configuration has been reloaded
  reload-success: "&aLe plugin a été rechargé avec succès."

  # Message when the configuration has been reloaded by console
  reload-success-console: "&cLe plugin a été rechargé avec succès."

