Options:
  # If this option is set to true, the tnt will not damage the water
  water-protection: true
  # If this option is set to True, the particles of the explosion will appear
  fake-explosion: true

Messages:
  # Message when the player does not have permission
  no-perm: "&cYou don't have permission to do this."

  # Message when the command is not correct
  invalid-usage: "&cThe use of this command is incorrect. Only the /cbp reload command is available."

  # Message when the configuration has been reloaded
  reload-success: "&aThe plugin has been successfully reloaded."

  # Message when the configuration has been reloaded by console
  reload-success-console: "&cThe plugin has been successfully reloaded."

