Options:
  # If this option is set to true, the tnt will not damage the water
  water-protection: true
  # If this option is set to True, the particles of the explosion will appear
  fake-explosion: true

Messages:
  # Message when the player does not have permission
  no-perm: "&cSie haben keine Erlaubnis, dies zu tun."

  # Message when the command is not correct
  invalid-usage: "&cDie Verwendung dieses Befehls ist nicht korrekt. Es ist nur der Befehl /cbp reload verfügbar."

  # Message when the configuration has been reloaded
  reload-success: "&aDas Plugin wurde erfolgreich neu geladen."

  # Message when the configuration has been reloaded by console
  reload-success-console: "&cDas Plugin wurde erfolgreich neu geladen."

