Options:
  # If this option is set to true, the tnt will not damage the water
  water-protection: true
  # If this option is set to True, the particles of the explosion will appear
  fake-explosion: true

Messages:
  # Message when the player does not have permission
  no-perm: "&cNo tienes permiso para hacer esto."

  # Message when the command is not correct
  invalid-usage: "&cEl uso de este comando es incorrecto. Sólo está disponible el comando /cbp reload."

  # Message when the configuration has been reloaded
  reload-success: "&aEl plugin ha sido recargado con éxito."

  # Message when the configuration has been reloaded by console
  reload-success-console: "&cEl plugin ha sido recargado con éxito."

